spring.application.name=applySystem
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/btteam?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Tokyo
spring.datasource.username=root
spring.datasource.password=root
# MyBatis \u306e\u8a2d\u5b9a
mybatis.mapper-locations=classpath*:/mybatis/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
#添付ファイルアップロードパス
upload.path=C:/pleiades/workspace/work_flow_system/upload
#HTMLの場所指定
spring.thymeleaf.prefix=classpath:/html/
spring.thymeleaf.suffix=.html
